# Generated by Django 5.2.4 on 2025-08-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
