# Generated by Django 5.2.4 on 2025-08-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='position',
        ),
    ]
