# Generated by Django 5.2.4 on 2025-08-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productvariantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
