# Generated by Django 5.2.4 on 2025-08-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productvariantimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(upload_to='variants/'),
        ),
        migrations.DeleteModel(
            name='ProductVariantImage',
        ),
    ]
