# Generated by Django 5.2.4 on 2025-08-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productvariant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color_code',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
