# Generated by Django 5.2.4 on 2025-08-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_productvariant_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color_codes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
