# Generated by Django 5.2.4 on 2025-08-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_productvariant_color_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color_name',
            field=models.CharField(max_length=50),
        ),
    ]
