# Generated by Django 5.2.4 on 2025-08-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_productvariant_color_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color_name')},
        ),
    ]
