# Generated by Django 5.2.4 on 2025-08-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='house_name_or_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
